version: '3.7'

x-common: &base
  image: dkron/dkron:3.2.1
  command: agent

networks:
  vpcbr:
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

services:
  server:
    <<: *base
    environment:
      DKRON_DATA_DIR: /ext/data
      DKRON_SERVER: 1
      DKRON_NODE_NAME: dkron1
      DKRON_BOOTSTRAP_EXPECT: 1
    volumes:
      - ./dkron.data:/ext/data
    ports:
      - 8888:8080
    networks:
      vpcbr:
        ipv4_address: 10.5.0.${TEST_NUMBER:-20}

  agents:
    <<: *base
    environment:
      DKRON_RETRY_JOIN: server
    networks:
      vpcbr:
    deploy:
      replicas: 1